# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be434ec06deb8024438d5cc844d077faa38fb5ae462640451a6068e959521735f35e481c5f40dad1c37c4affe3a1169ac7af283c84bcb629e04b74066663248

test:
  secret_key_base: 805106b2fe651c214950238c489b01a8dc96e267df7e193d4746d750d5aaaac14610ba7d530fae6aa17236bb05c47177b464ea45155f5107d3e3ee196d0ae502

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
